Added a path setting flag. removed prerequisites.

diff --git a/run.in b/run.in
--- a/run.in
+++ b/run.in
@@ -7,7 +7,19 @@ fail () {
      exit 1
 }
 
-(( $# > 0 )) || fail "need >= 1 arguments (got $#)"
+OPTIND=1
+while getopts :p option
+do case "$option" in
+       p ) # set limited path
+           export PATH=/bin:/usr/bin:/opt/local/bin:@builddir@/tmp/root/bin;;
+       : ) # getops reporting missing argument
+           printf "Short option \"%s\" missing argument" "$OPTARG" >&2
+           exit 1;;
+   esac
+done
+shift $((OPTIND-1))
+
+(( $# > 0 )) || fail "need a command"
 
 command=$1
 shift
@@ -38,14 +50,6 @@ case $command in
          echo "That's as far as it gets for now. Add to it when you have new content."
          exit 1
          ;;
-     # prerequisites
-     pre )
-         PATH=/bin:/usr/bin:/opt/local/bin:$PWD/tmp/root/bin @srcdir@/configure
-         make -f prerequisites.mk clean
-         make -f prerequisites.mk
-         ;;
      * ) fail "Unknown command \"$command\""
     ;;
 esac
-
-
